# This file is part of the DVSwitch Mode Switcher project.
#
# (c) 2024 Caleb <ko4uyj@gmail.com>
#
# For the full copyright and license information,
# see the LICENSE file that was distributed with this source code.

# Defines the talkgroup id's and aliases for the modes
modes:
  - DMR:
      talkgroups:
        - tgid: "4000"
          alias: DISCONNECT
        - tgid: "9990#"
          alias: PARROT
        - tgid: "91"
          alias: WorldWide
        - tgid: "3100"
          alias: USA
          - tgid: "31010"
          alias: Alabama-Link
        - tgid: "yourtgifpasswordhere@tgif.network:62031!0"
          alias: TGIFNetwork Select
          - tgid: "yourbrandmeisterpasswordhere@3102.repeater.net:62031!4000"
          alias: Brandmeister Select
  - YSF:
      talkgroups:
        - tgid: "register.ysfreflector.de:42020"
          alias: PARROT
        - tgid: "americalink.hamfm.com:42000"
          alias: US-AMERICA-LINK
        - tgid: "ysf.kansascitywide.com:42000"
          alias: US-KCWide
  - P25:
      talkgroups:
        - tgid: "12"
          alias: P25 1
        - tgid: "23"
          alias: P25 2
  - DSTAR:
      talkgroups:
        - tgid: "13"
          alias: DSTAR 1
        - tgid: "24"
          alias: DSTAR 2
  - NXDN:
      talkgroups:
        - tgid: "14"
          alias: NXDN 1
        - tgid: "25"
          alias: NXDN 2
